# Generated by Django 5.1.1 on 2025-04-12 21:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='farm_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pictures'),
        ),
    ]
