services:
  - type: web
    name: agriconnect
    runtime: python
    rootDirectory: backend 
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate &&
      gunicorn agriconnect.wsgi:application --timeout 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agriconnect_db_9mrf
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"  # Temporarily set to True for debugging
      - key: ALLOWED_HOSTS
        value: "*"  # Temporarily allow all hosts