services:
  - type: web
    name: agriconnect-backend
    runtime: python
    buildCommand: |
      pip install -r backend/requirements.txt &&
      python backend/manage.py collectstatic --noinput
    startCommand: "cd backend && gunicorn agriconnect.wsgi:application --timeout 120"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agriconnect_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "agriconnect-app.vercel.app,your-render-url.onrender.com"