services:
  - type: web
    name: agriconnect-backend
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn agriconnect.wsgi:application"
    runtime: python
    plan: free
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: agriconnect-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
    autoDeploy: true

databases:
  - name: agriconnect-db
    plan: free
