services:
  - type: web
    name: agriconnect
    runtime: python
    rootDirectory: backend 
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      startCommand: bash scripts/deploy.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agriconnect_db_z6u8
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "agriconnect-trpn.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "agriconnect.settings"