services:
  - type: web
    name: agriconnect-backend
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn agriconnect.wsgi:application"
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - backend/** 
        - build.sh
        - render.yaml
        - manage.py
        - agriconnect/**

    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: agriconnect-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: agriconnect-db
    plan: free
