services:
  - type: web
    name: agriconnect-backend
    runtime: python
    buildCommand: "cd backend && chmod +x build.sh && ./build.sh"
    startCommand: "cd backend && gunicorn agriconnect.wsgi:application --timeout 120"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agriconnect_db
          property: connectionString