services:
  - type: web
    name: agriconnect
    runtime: python
    rootDirectory: backend 
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations
      python manage.py migrate
    startCommand: "gunicorn agriconnect.wsgi:application --timeout 120" 
    envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: agriconnect_db_y3by
        property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"  # Should be False in production
      - key: ALLOWED_HOSTS
        value: "agriconnect-app.vercel.app,agriconnect-trpn.onrender.com"