services:
  - type: web
    name: agriconnect-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn agriconnect.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agriconnect_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "agriconnect-app.vercel.app,your-render-url.onrender.com"
      - key: EMAIL_HOST_USER
        value: your-email@example.com
      - key: EMAIL_HOST_PASSWORD
        value: your-email-password
      - key: GOOGLE_CLIENT_ID
        value: your-google-client-id
      - key: GOOGLE_CLIENT_SECRET
        value: your-google-client-secret