# Generated by Django 5.1.1 on 2025-04-01 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='farmer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='name_on_card',
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='expired_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free_trial', 'FREE_TRIAL'), ('premium', 'PREMIUM'), ('enterprise', 'ENTERPRISE')], default='free_trial', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('trial', 'TRIAL'), ('expired', 'EXPIRED'), ('canceled', 'CANCELED'), ('payment_pending', 'PAYMENT_PENDING')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ending_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'MPESA'), ('bank', 'Bank')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
        ),
    ]
