# Generated by Django 5.1.1 on 2025-04-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_rename_farmer_subscription_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'MPESA'), ('card', 'Credit Card')], max_length=50, null=True),
        ),
    ]
