# Generated by Django 5.1.1 on 2025-03-22 14:07

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_organic',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default="General", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default="unit", max_length=50),
            preserve_default=False,
        ),
    ]
