# Generated by Django 5.1.1 on 2025-03-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_description_remove_product_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='unit', max_length=50),
        ),
    ]
