# Generated by Django 5.1.1 on 2025-03-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='farm',
            name='ratings',
            field=models.JSONField(default=list),
        ),
    ]
