# Generated by Django 5.1.1 on 2025-03-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='specialty',
        ),
    ]
