# Generated by Django 5.1.1 on 2025-03-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_rating_farm_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='sustainability',
            field=models.TextField(blank=True, null=True),
        ),
    ]
