# Generated by Django 5.1.1 on 2025-03-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_remove_farm_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='specialty',
            field=models.CharField(default='Agriculture', max_length=255),
        ),
    ]
