# Generated by Django 5.1.1 on 2025-03-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='sustainability',
            field=models.TextField(blank=True, null=True),
        ),
    ]
