# Generated by Django 5.1.1 on 2025-03-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_phone_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
