# Generated by Django 5.1.1 on 2025-03-23 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_farmerprofile_farm_name'),
        ('farms', '0003_farm_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='farm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to='farms.farm'),
        ),
    ]
