# Generated by Django 5.1.1 on 2025-03-23 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('mpesa', 'MPESA'), ('bank', 'Bank')], max_length=50)),
                ('mpesa_number', models.CharField(blank=True, max_length=15, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=3, null=True)),
                ('name_on_card', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
